### PR TITLE
Update plugin.xml

### PR DESCRIPTION
**Pull request by BorzdeG**
Added dependencies for the plugin

### CODE REVIEW

**Comment by sburlyaev** [comment]
Hi @BorzdeG,
Thanks for the request! But can you please a little bit explain why it should be there?

**Comment by BorzdeG** [comment]
If you disable the bundle-plugin "Terminal", then inclusion of this plugin does not make sense - they can not be used

**Comment by sburlyaev** [comment]
Actually the plugin doesn't use jetbrains-terminal. It is just a launcher that open OS native terminal in a separate window. So, if you disable the jetbrains-terminal you still be able to use this one.

**Comment by BorzdeG** [comment]
Ok

**Pull request closed without merging**
